cpsat:
  temps_max_secondes: 600
fichiers:
  donnees: examples/volleyball/config_volley.xlsx
  sortie: examples/volleyball/calendrier_volley_greedy.xlsx
greedy:
  nb_essais: 5
planification:
  nb_semaines: 10
  strategie: greedy
